In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
DF_visit = pd.read_csv('Visit data.csv')
DF_econ = pd.read_csv("Economic data.csv")

In [3]:
DF_visit.head()

,Park Name,Park Code,State,Year,Month,Recreation Visitors,Non-Recreation Visitors,Recreation Visitor Hours,Non-Recreation Hours,Concession Lodging,Tent Campers,RV Campers,Concession Camping,Backcountry Campers,Misc Campers,Non-Recreation Overnight Stays,Total Overnight Stays
0,Crater Lake National Park,CRLA,OR,2015,January,10489,2100,39953,1050,0,0,0,0,162,0,0,162.0
1,Crater Lake National Park,CRLA,OR,2015,February,8635,2400,33682,1200,0,0,0,0,173,0,0,173.0
2,Crater Lake National Park,CRLA,OR,2015,March,13938,2800,54242,1400,0,0,0,0,273,0,0,273.0
3,Crater Lake National Park,CRLA,OR,2015,April,16918,4800,63625,2400,62,0,0,0,171,0,0,233.0
4,Crater Lake National Park,CRLA,OR,2015,May,48217,4900,274731,2450,3457,0,0,2309,224,0,0,5990.0

HEYYY GUYS

In [8]:
DF_visit['Month_Num'] = pd.to_datetime(DF_visit['Month'], format='%B').dt.month
DF_visit['Date'] = pd.to_datetime(DF_visit.Year.astype(str) + '/' + DF_visit.Month_Num.astype(str) + '/01')
DF_visit["Join Code"] = DF_visit["Park Code"] + DF_visit["Year"].astype(str)
DF_visit.head()

,Park Name,Park Code,State,Year,Month,Recreation Visitors,Non-Recreation Visitors,Recreation Visitor Hours,Non-Recreation Hours,Concession Lodging,Tent Campers,RV Campers,Concession Camping,Backcountry Campers,Misc Campers,Non-Recreation Overnight Stays,Total Overnight Stays,Month_Num,Date,Join Code
0,Crater Lake National Park,CRLA,OR,2015,January,10489,2100,39953,1050,0,0,0,0,162,0,0,162.0,1,2015-01-01,CRLA2015
1,Crater Lake National Park,CRLA,OR,2015,February,8635,2400,33682,1200,0,0,0,0,173,0,0,173.0,2,2015-02-01,CRLA2015
2,Crater Lake National Park,CRLA,OR,2015,March,13938,2800,54242,1400,0,0,0,0,273,0,0,273.0,3,2015-03-01,CRLA2015
3,Crater Lake National Park,CRLA,OR,2015,April,16918,4800,63625,2400,62,0,0,0,171,0,0,233.0,4,2015-04-01,CRLA2015
4,Crater Lake National Park,CRLA,OR,2015,May,48217,4900,274731,2450,3457,0,0,2309,224,0,0,5990.0,5,2015-05-01,CRLA2015

In [12]:
DF_visit_by_year = DF_visit.groupby(["Park Code","Year"]).agg({"Park Name": "first", "State": "first","Recreation Visitors":"sum", "Non-Recreation Visitors":"sum","Recreation Visitor Hours":"sum", "Non-Recreation Hours":"sum", "Concession Lodging":"sum", "Tent Campers":"sum", "RV Campers":"sum", "Concession Camping":"sum","Backcountry Campers":"sum","Misc Campers":"sum", "Non-Recreation Overnight Stays":"sum", "Total Overnight Stays":"sum", "Join Code":"first"})
DF_visit_by_year.head()

                           Park Name State  Recreation Visitors  \
Park Code Year
ACAD      2015  Acadia National Park   ME               2811184
          2016  Acadia National Park   ME               3303393
          2017  Acadia National Park   ME               3509271
          2018  Acadia National Park   ME               3537575
          2019  Acadia National Park   ME               3437286

                Non-Recreation Visitors  Recreation Visitor Hours  \
Park Code Year
ACAD      2015                    47100                  14452151
          2016                    47100                  22698596
          2017                    47100                  24014370
          2018                    47100                  23613754
          2019                    47100                  23195664

                Non-Recreation Hours  Concession Lodging  Tent Campers  \
Park Code Year
ACAD      2015                 47100                   0        135000
          2016                 47100                   0        152811
          2017                 47100                   0        152586
          2018                 47100                   0        144744
          2019                 47100                   0        140985

                RV Campers  Concession Camping  Backcountry Campers  \
Park Code Year
ACAD      2015       32094                   0                 1233
          2016       46629                 977                 1324
          2017       55812                1657                 1597
          2018       58215                1364                 1472
          2019       57696                1090                 1284

                Misc Campers  Non-Recreation Overnight Stays  \
Park Code Year
ACAD      2015          8343                               0
          2016          8563                               0
          2017         10889                               0
          2018         11698                               0
          2019         11674                               0

                Total Overnight Stays Join Code
Park Code Year
ACAD      2015               176670.0  ACAD2015
          2016               210304.0  ACAD2016
          2017               222541.0  ACAD2017
          2018               217493.0  ACAD2018
          2019               212729.0  ACAD2019

In [14]:
DF_econ["Join Code"] = DF_econ["Code"] + DF_econ["Year"].astype(str)
DF_econ.head()

,Year,Code,Name,Recreation Visits,Visitor\nSpending,Jobs Supported,Labor Income,Value Added,Economic\nOutput,Join Code
0,2024,ACAD,Acadia National Park,"3,961,661","$538,906","5,304","$243,133","$459,921","$744,545",ACAD2024
1,2024,ARCH,Arches National Park,"1,466,528","$287,785","2,502","$94,522","$183,289","$312,122",ARCH2024
2,2024,BADL,Badlands National Park,"1,094,245","$143,206","1,410","$58,901","$111,301","$191,413",BADL2024
3,2024,BIBE,Big Bend National Park,"561,458","$56,817",585,"$17,269","$34,443","$63,707",BIBE2024
4,2024,BISC,Biscayne National Park,"512,213","$39,679",362,"$19,190","$34,520","$55,023",BISC2024

In [15]:
DF_all = pd.merge(DF_visit_by_year, DF_econ, on = "Join Code")
DF_all.head()

,Park Name,State,Recreation Visitors,Non-Recreation Visitors,Recreation Visitor Hours,Non-Recreation Hours,Concession Lodging,Tent Campers,RV Campers,Concession Camping,...,Join Code,Year,Code,Name,Recreation Visits,Visitor\nSpending,Jobs Supported,Labor Income,Value Added,Economic\nOutput
0,Acadia National Park,ME,2811184,47100,14452151,47100,0,135000,32094,0,...,ACAD2015,2015,ACAD,Acadia National Park,"2,811,184","$247,910.80","3,878","$102,112.70","$172,526.10","$304,623.50"
1,Acadia National Park,ME,3303393,47100,22698596,47100,0,152811,46629,977,...,ACAD2016,2016,ACAD,Acadia National Park,"3,303,394","$274,208.80","4,195","$111,087.10","$188,275.10","$332,786.30"
2,Acadia National Park,ME,3509271,47100,24014370,47100,0,152586,55812,1657,...,ACAD2017,2017,ACAD,Acadia National Park,"3,509,271","$284,459.80","4,163","$107,621.50","$185,248.30","$338,873.80"
3,Acadia National Park,ME,3537575,47100,23613754,47100,0,144744,58215,1364,...,ACAD2018,2018,ACAD,Acadia National Park,"3,537,575","$387,654","5,602","$171,668","$304,982","$521,454"
4,Acadia National Park,ME,3437286,47100,23195664,47100,0,140985,57696,1090,...,ACAD2019,2019,ACAD,Acadia National Park,"3,437,286","$379,517","5,474","$168,284","$298,961","$510,962"

In [ ]:
DF_all.to_csv("Visit Econ Data.csv")
heyyyy