In [105]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Merging Datasets

In [106]:
visits = pd.read_csv('New-370 data - all (2).csv')

In [107]:
economics = pd.read_csv("New-370 data - Economics.csv")

In [111]:
## grouping visits by the year and park 

byYearPark = visits.groupby(by=["Year","Park Name", 'Park Code','State']).sum().reset_index()
byYearPark = byYearPark.drop(columns=['Month'])
byYearPark = byYearPark[byYearPark['Year']<2025]
byYearPark.head()

,Year,Park Name,Park Code,State,Recreation Visitors,Non-Recreation Visitors,Recreation Visitor Hours,Non-Recreation Hours,Concession Lodging,Tent Campers,RV Campers,Concession Camping,Backcountry Campers,Misc Campers,Non-Recreation Overnight Stays,Total Overnight Stays
0,2015,Acadia National Park,ACAD,ME,2811184,47100,14452151,47100,0,135000,32094,0,1233,8343,0,176670
1,2015,Arches National Park,ARCH,UT,1399247,0,5420170,0,0,27158,16565,0,1208,6005,0,50933
2,2015,Badlands National Park,BADL,SD,989354,65911,4531214,32956,9474,4627,856,39444,1445,215,0,56062
3,2015,Big Bend National Park,BIBE,TX,381747,2364,9504644,7092,50747,53963,24420,9643,32435,33945,0,205153
4,2015,Biscayne National Park,BISC,FL,508164,0,1672449,0,0,1860,0,0,0,4305,0,6165

In [112]:
## merging visits and economics together + getting rid of some extra columns 
visits_economics = pd.merge(byYearPark, economics, left_on=['Year', 'Park Code'], right_on=['Year', 'Code'], how='inner')
visits_economics = visits_economics.drop(columns = ["Name", "Recreation Visits", "Code"])

In [113]:
visits_economics.head()

,Year,Park Name,Park Code,State,Recreation Visitors,Non-Recreation Visitors,Recreation Visitor Hours,Non-Recreation Hours,Concession Lodging,Tent Campers,...,Concession Camping,Backcountry Campers,Misc Campers,Non-Recreation Overnight Stays,Total Overnight Stays,Visitor\nSpending ($),Jobs Supported,Labor Income ($),Value Added ($),Economic\nOutput ($)
0,2015,Acadia National Park,ACAD,ME,2811184,47100,14452151,47100,0,135000,...,0,1233,8343,0,176670,247910.8,3878.0,102112.7,172526.1,304623.5
1,2015,Arches National Park,ARCH,UT,1399247,0,5420170,0,0,27158,...,0,1208,6005,0,50933,162718.2,2711.0,67949.5,122729.0,216319.6
2,2015,Badlands National Park,BADL,SD,989354,65911,4531214,32956,9474,4627,...,39444,1445,215,0,56062,62209.2,1015.0,24363.7,40138.3,77537.9
3,2015,Big Bend National Park,BIBE,TX,381747,2364,9504644,7092,50747,53963,...,9643,32435,33945,0,205153,33426.3,503.0,11340.1,20658.1,37168.8
4,2015,Biscayne National Park,BISC,FL,508164,0,1672449,0,0,1860,...,0,0,4305,0,6165,31927.3,450.0,17612.1,27499.2,44346.6

# EDA

### Summary statistics

In [126]:
visits_economics.describe()

,Year,Recreation Visitors,Non-Recreation Visitors,Recreation Visitor Hours,Non-Recreation Hours,Concession Lodging,Tent Campers,RV Campers,Concession Camping,Backcountry Campers,Misc Campers,Non-Recreation Overnight Stays,Total Overnight Stays,Visitor\nSpending ($),Jobs Supported,Labor Income ($),Value Added ($),Economic\nOutput ($)
count,600.000000,6.000000e+02,6.000000e+02,6.000000e+02,6.000000e+02,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,6.000000e+02,6.000000e+02,600.000000,6.000000e+02,6.000000e+02,6.000000e+02
mean,2019.500000,1.412268e+06,3.957252e+05,1.146075e+07,2.654515e+05,43075.733333,38985.461667,24215.833333,17556.211667,22607.528333,7796.353333,450.735000,1.539616e+05,1.562969e+05,2095.968333,7.349316e+04,1.240750e+05,2.121814e+05
std,2.874678,1.946318e+06,1.465275e+06,1.982571e+07,8.673624e+05,131819.308223,69691.341451,42701.273377,78471.395285,48376.570396,15154.846949,1712.680532,2.914938e+05,2.461739e+05,3402.079113,1.229229e+05,2.038467e+05,3.469924e+05
min,2015.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
25%,2017.000000,2.720400e+05,0.000000e+00,1.390753e+06,0.000000e+00,0.000000,0.000000,0.000000,0.000000,382.500000,0.000000,0.000000,9.645250e+03,2.798528e+04,351.750000,1.159450e+04,1.999650e+04,3.429625e+04
50%,2019.500000,6.659130e+05,7.650500e+03,3.675749e+06,1.577800e+04,0.000000,6184.500000,3752.500000,0.000000,3525.000000,824.500000,0.000000,4.233600e+04,6.187200e+04,823.500000,2.771950e+04,4.843900e+04,8.237100e+04
75%,2022.000000,1.704201e+06,6.363475e+04,1.093750e+07,8.404750e+04,18488.750000,49748.500000,29430.000000,0.000000,27069.500000,8300.250000,0.000000,1.550908e+05,1.565978e+05,2126.250000,7.253425e+04,1.261542e+05,2.104223e+05
max,2024.000000,1.416155e+07,1.123478e+07,1.035739e+08,5.617391e+06,938418.000000,588701.000000,376744.000000,616089.000000,337790.000000,89472.000000,12925.000000,2.062671e+06,2.198538e+06,33748.000000,1.267581e+06,2.000786e+06,3.397905e+06

In [115]:
visits.describe()

,Year,Recreation Visitors,Non-Recreation Visitors,Recreation Visitor Hours,Non-Recreation Hours,Concession Lodging,Tent Campers,RV Campers,Concession Camping,Backcountry Campers,Misc Campers,Non-Recreation Overnight Stays,Total Overnight Stays
count,7920.000000,7.920000e+03,7.920000e+03,7.920000e+03,7920.000000,7920.000000,7920.000000,7920.000000,7920.000000,7920.000000,7920.000000,7920.000000,7920.000000
mean,2020.000000,1.183488e+05,3.309108e+04,9.550774e+05,22233.509091,3622.548359,3232.742424,2031.939141,1477.166288,1858.321465,652.305177,36.792045,12849.848611
std,3.162477,2.011076e+05,1.264970e+05,2.170515e+06,77496.278277,14044.597612,8441.268642,5061.824709,10890.371389,5461.584677,1637.493130,185.225800,34159.094912
min,2015.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2017.000000,1.072150e+04,0.000000e+00,5.204350e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,52.000000
50%,2020.000000,4.537750e+04,4.460000e+02,1.931590e+05,600.000000,0.000000,46.000000,0.000000,0.000000,84.000000,0.000000,0.000000,1307.000000
75%,2023.000000,1.282242e+05,5.797750e+03,7.211620e+05,6150.000000,897.250000,1852.500000,1520.000000,0.000000,675.000000,335.000000,0.000000,9261.500000
max,2025.000000,1.739720e+06,1.334690e+06,2.021239e+07,685776.000000,153527.000000,121937.000000,78060.000000,163452.000000,62848.000000,14436.000000,6165.000000,360221.000000

### Top 5 states with most recreation visitors

In [125]:
visits.groupby(by='State').sum().drop(columns =["Month", "Park Name", "Park Code","Year"]).sort_values('Recreation Visitors', ascending = False).head()

,Recreation Visitors,Non-Recreation Visitors,Recreation Visitor Hours,Non-Recreation Hours,Concession Lodging,Tent Campers,RV Campers,Concession Camping,Backcountry Campers,Misc Campers,Non-Recreation Overnight Stays,Total Overnight Stays
State,,,,,,,,,,,,
TN/NC,133545617,117949073,899504359,58974546,116235,1981859,1467856,0,1021373,288196,0,4875518
UT,112958178,5940288,600535936,2412863,1364857,2265688,1923180,0,1077974,357735,0,6419923
CA,112937284,2593792,1467105944,47411390,8176137,8952944,5260515,384257,2609951,1557528,102492,27043820
WY,84033041,30653692,1113879896,25050836,8099082,697029,579520,9288048,873851,88586,0,19626129
AZ,72645069,36681532,915499866,9389633,5904021,1396547,711534,462561,3230326,232272,0,11937267

### Top 5 Years with most recreation visitors

In [127]:
visits.groupby(by='Year').sum().drop(columns =["Month", "Park Name", "Park Code","State"]).sort_values('Recreation Visitors', ascending = False).head()

,Recreation Visitors,Non-Recreation Visitors,Recreation Visitor Hours,Non-Recreation Hours,Concession Lodging,Tent Campers,RV Campers,Concession Camping,Backcountry Campers,Misc Campers,Non-Recreation Overnight Stays,Total Overnight Stays
Year,,,,,,,,,,,,
2024,91186076,24624441,689328121,16946841,2934501,2319208,1625650,1049104,1291922,505069,31513,9774561
2025,89961848,24646266,687763596,16818501,2845143,2212043,1563458,1165430,1153389,488445,20952,9393865
2023,89671691,24507664,704825539,16908622,2605545,2138044,1509415,1025902,1323345,518283,29331,9095365
2021,89614755,22200135,693100034,15347671,2081419,2063240,1374656,1025340,1512831,415743,24156,8438590
2019,88726379,24018185,731746982,15893952,2909336,2509363,1486627,973338,1292999,444026,21449,9580719

### Top 5 Parks with most recreation visitors

In [128]:
visits.groupby(by='Park Name').sum().drop(columns =["Month", "Year", "Park Code","State"]).sort_values('Recreation Visitors', ascending = False).head()

,Recreation Visitors,Non-Recreation Visitors,Recreation Visitor Hours,Non-Recreation Hours,Concession Lodging,Tent Campers,RV Campers,Concession Camping,Backcountry Campers,Misc Campers,Non-Recreation Overnight Stays,Total Overnight Stays
Park Name,,,,,,,,,,,,
Great Smoky Mountains National Park,133545617,117949073,899504359,58974546,116235,1981859,1467856,0,1021373,288196,0,4875518
Grand Canyon National Park,56345088,291007,884827754,291007,5904021,1396547,711534,462561,3191264,232272,0,11898205
Zion National Park,49134947,240900,317462174,60225,840289,1287241,878456,0,179586,243025,0,3428604
Rocky Mountain National Park,46853350,96250,314962021,288750,0,1071922,543179,0,442772,57247,0,2115120
Yellowstone National Park,46572212,13671773,878447486,8068917,6103608,696833,579147,5409404,443067,83812,0,13315875

In [130]:
visits.groupby(by='Park Name').sum().drop(columns =["Month", "Year", "Park Code","State"]).sort_values('Recreation Visitors', ascending = True).head()

,Recreation Visitors,Non-Recreation Visitors,Recreation Visitor Hours,Non-Recreation Hours,Concession Lodging,Tent Campers,RV Campers,Concession Camping,Backcountry Campers,Misc Campers,Non-Recreation Overnight Stays,Total Overnight Stays
Park Name,,,,,,,,,,,,
Gates of the Arctic National Park & Preserve,109644,0,1351458,0,0,0,0,0,54207,0,0,54207
Kobuk Valley National Park,143988,71822,1270068,1375264,0,0,0,0,59188,0,60012,119200
Lake Clark National Park & Preserve,189735,14818,1802782,281690,0,0,0,0,63458,1238,11457,76153
Isle Royale National Park,268707,1423,13804508,294304,108855,54906,0,2376,278979,118335,12202,575653
North Cascades National Park,330597,0,5900071,0,0,0,0,0,242717,0,0,242717